baseURL = 'https://michaelthomasletts.com/'
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
title = 'Mike Letts'
theme = "hugo-bearcub"
author = "Mike Letts"
copyright = "Â© Copyright 2025, Michael Letts"
enableRobotsTXT = true

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/lettsmichael/'
    weight = 2  
  [[menus.main]]
    name = 'GitHub'
    url = 'https://www.github.com/michaelthomasletts'
    weight = 3
  [[menus.main]]
    name = 'PyPI'
    url = 'https://www.pypi.org/user/lettsmt/'
    weight = 4
  [[menus.main]]
    identifier = 'blog'
    name = 'Blog'
    pageRef = '/blog/'
    weight = 5
  [[menus.main]]
    name = 'Spotify'
    url = 'https://open.spotify.com/user/22de5bcpae7ccoa32fejlddcq'
    weight = 6
  [[menus.main]]
    identifier = 'contact'
    name = 'Contact'
    pageRef = '/contact'
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
    [markup.goldmark.renderer]
      unsafe = true

[params]
  madeWith  = "Made with Hugo & BearCub"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"